### PR TITLE
MNT: Re-rendered with conda-smithy 2.3.0

### PR DESCRIPTION
**Pull request by damianavila**
Trying 2.3.0 now.

### CODE REVIEW

**Comment by jakirkham** [comment]
Friendly reminder to make changes on your fork and submit them as PRs.

**Comment by damianavila** [comment]
> Friendly reminder to make changes on your fork and submit them as PRs.

Upps... sorry about that... I missed that point. Will do it in the future.

**Comment by jakirkham** [comment]
No worries. We had been putting it in the feedstock Readme and the about page. Maybe there are other places to document this? Maybe we need to have something in the docs explaining why this is best practice? Other suggestions?

**Comment by damianavila** [comment]
> something in the docs explaining why this is best practice

I think that would be nice. I did not find a reference in the docs... but maybe I missed it.

**Pull request merged**
