### PR TITLE
try against conda-forge vs2015

### PR DESCRIPTION
**Pull request by bollwyvl**
Still seeing issues with vs2015, most likely:

https://github.com/conda-forge/staged-recipes/pull/710

### CODE REVIEW

**Comment by msarahan** [comment]
The issue here is that you do not have %CONDA_INSTALL_LOCN%\Library\bin on PATH, so any runtimes are not being found.

I'm submitting a patch against your branch here that should work.

**Comment by bollwyvl** [comment]
Hm, looks like none of the phantom tests are working... we had already dropped them from Linux, so perhaps it makes sense to just drop the tests altogether, and fall back to import tests.

**Comment by msarahan** [comment]
Might want to also restart this to see if the new conda build helps with the win py35 post link at all. I'd do that, but I don't have authority on this feedstock.

**Comment by jakirkham** [comment]
> Might want to also restart this...

Done. 😄

**Comment by bollwyvl** [comment]
> Done. 😄

Whoops. Well, figured i'd regenerate and add the env fix... but the test fails are concerning.

**Comment by bollwyvl** [comment]
Well, everything worked once (sort of) on ec1aafb.

Looks like the new pyzmq did the trick on windows... but I'm trying again to see if the tests can be run there as well.

**Comment by bollwyvl** [comment]
Ah, and the previously noted issue https://github.com/conda-forge/nbpresent-feedstock/issues/3 was still appearing, so dropping the tests there again for the time being.

**Comment by msarahan** [comment]
Hooray! Finally fixed windows! Nice work.

**Comment by bollwyvl** [comment]
Well, _building at all_ is much better than _not building_, so we'll take it over _building with all the tests running_. Going to merge this...

**Pull request merged**
