### PR TITLE
Fix build.sh: install post-link/pre-unlink scripts to build environment instead of work dir (Fixes #20)

### LINKED ISSUE #20: As of 2.1.1, Post-link.sh and pre-unlink.sh are not included in conda-forge builds
As of 2.1.1 (PR #18), the pre-unlink and post-link scripts are not being included in the conda-forge build (because the scripts were moved to the source repo, and conda-forge doesn't seem to pick them up from their new location). This means that the notebook extension is not enabled by default after installation. (It can be manually enabled with `python -m nb_conda_kernels.install --enable` )

This change was implemented by https://github.com/Anaconda-Platform/nb_conda_kernels/pull/82, and motivated by https://github.com/Anaconda-Platform/nb_conda_kernels/issues/73

The fix is likely to coerce the conda-forge build to include these scripts somehow.

### PR DESCRIPTION
**Pull request by tjd2002**
Ping @mcg1969. This now builds OK on my local machine. Fixes #20

### CODE REVIEW

**Comment by mcg1969** [comment]
Ah! Good find. Should we do the equivalent for Windows in `bld.bat`?

**Comment by tjd2002** [comment]
Almost certainly, but I don’t speak .bat, and I don’t have a Windows machine to test on. :-/

**Comment by mcg1969** [comment]
I remain unable to edit here, but this is what I propose for now. If you can do it, I'd like to take my chances and merge—because in the absolute worst case, we've fixed Unix, and not made Windows any worse.
```
%PYTHON% setup.py install --single-version-externally-managed --record=record.txt
mkdir %PREFIX%\Scripts
copy %SRC_DIR%\conda-recipe\post-link.bat %PREFIX%\Scripts\.nb_conda_kernels-post-link.bat
copy %SRC_DIR%\conda-recipe\pre-unlink.bat %PREFIX%\Scripts\.nb_conda_kernels-pre-unlink.bat
```

**Comment by mcg1969** [comment]
Ah, and we need to increment the build number, too.

**Comment by ocefpaf** [comment]
@tjd2002 I'll merge this and finish the Windows and the bump in another PR.
Thanks!

**Pull request merged**
