### PR TITLE
Update to 2.1.1

### PR DESCRIPTION
**Pull request by mcg1969**
Note: the pre- and post-link scripts are now hosted and controlled in the [source repo](https://github.com/Anaconda-Platform/nb_conda_kernels/tree/master/conda-recipe).

@bollwyvl, do you still want to be listed as a maintainer here? I can remove you if you like.

### CODE REVIEW

**Comment by mcg1969** [comment]
Maintainers: note a key change here—I have moved the responsibility to maintain the post-link and pre-unlink scripts to the source repo. They need to be tested using the full test suite, after all.

**Comment by bollwyvl** [comment]
Yes, I think unmaintainerizing me would be appropriate at this time!
Thanks!

**Comment by mcg1969** [comment]
Done, @bollwyvl, thanks for responding!

**Comment by mcg1969** [comment]
@ocefpaf @damianavila any chance we can get it merged?

**Comment by ocefpaf** [comment]
I was hoping that @bollwyvl would merge this since he is passing the baton here.

**Pull request merged**
